# Generated by Django 3.2.9 on 2022-01-03 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulofarmacia',
            name='fecharda',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
