# Generated by Django 3.2.9 on 2022-01-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_articulofarmacia_fecharda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulofarmacia',
            name='agnoCaducidad',
        ),
        migrations.RemoveField(
            model_name='articulofarmacia',
            name='mesCaducidad',
        ),
    ]
