# Generated by Django 3.2.9 on 2022-01-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220103_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulofarmacia',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaFarmacia',
        ),
    ]
