# Generated by Django 3.2.9 on 2022-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220103_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulofarmacia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulofarmacia',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
