# Generated by Django 3.2.9 on 2022-01-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_articulofarmacia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulofarmacia',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
