# Generated by Django 3.2.9 on 2022-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_articulofarmacia_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloFarmaciaLiquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=75)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecharda', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'ArticuloFarmaciaLiquido',
                'verbose_name_plural': 'ArticulosFarmaciaLiquido',
            },
        ),
    ]
